# REV006 Wed Jul 17 19:06:01 WIB 2019
# REV004 Mon Mar  4 19:43:56 WIB 2019
# REV001 Mon Mar  4 18:16:23 WIB 2019
# START  Mon Mar  4 18:07:18 WIB 2019

title: Pamulang
description: > 
   (V006 190717) Kisah warga Pamulang, katanya sih.
author: Cicak Bin Kadal
theme: jekyll-theme-midnight
show_downloads: false
share: false
github: [metadata]
encoding: UTF-8
timezone: Asia/Jakarta

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


