# REV001 Mon Mar  4 18:16:23 WIB 2019
# START  Mon Mar  4 18:07:18 WIB 2019

title: Pamulang (001)
description: > 
   Kisah seorang warga bingung menjelang April 2019
author: Cicak Bin Kadal
theme: jekyll-theme-midnight
# theme: jekyll-theme-time-machine
show_downloads: true
share: true
github: [metadata]

